### ISSUE TITLE
We need an extra space for the numbers on at the top of Figures 2 and 3

### ISSUE THREAD

**Issue by aous72** [sandflow/rfc-j2k-scl#3]
The current format is 
![image](https://github.com/sandflow/rfc-j2k-scl/assets/7401883/c2eaad4b-40a9-4489-af6e-785e319ee82c)
This should be
![image](https://github.com/sandflow/rfc-j2k-scl/assets/7401883/a264ac47-2c3a-497f-bce7-cf08a0b0df50)
Notice the shift by one space to the right for the two rows of numbers at the top of the figure.
In other words, the numbers should be above the (-) symbol not the (+).

This is true for Figure 2 and 3.

Thank you.

Kind regards,
Aous.

**Comment by palemieux** [comment]
Closed by e104dd7b392e37484806ecea1aa2fe693c5542fa
