### ISSUE TITLE
fix formatting of ASCII ART in PDF render

### ISSUE THREAD

**Issue by michaeldsmith** [sandflow/rfc-j2k-scl#6]
The PDF render appears to show ill-formatted ASCII art in FIG 1-4.  Could its be a spaces vs tabs issue, or something else?

FIG 1
![image](https://github.com/sandflow/rfc-j2k-scl/assets/37905569/3dcdd62c-3451-477d-bd2a-d0ad24f281d9)

FIG 2
![image](https://github.com/sandflow/rfc-j2k-scl/assets/37905569/d9dacce7-3f2e-4272-ade8-a0544da5d7a1)

FIG 3
![image](https://github.com/sandflow/rfc-j2k-scl/assets/37905569/e0ea9f3c-dc0f-429c-9406-eb3f5474e27d)

FIG 4
![image](https://github.com/sandflow/rfc-j2k-scl/assets/37905569/2d6c0a51-a368-4413-ae14-621a252e3534)

**Comment by palemieux** [comment]
Fixed at 6f44a2d2b1e0065b5d8b532bece0603b767b8e4a

https://github.com/sandflow/rfc-j2k-scl/blob/gh-pages/index.txt
