### ISSUE TITLE
5.3 text references Figure 1 instead of Figure 2

### ISSUE THREAD

**Issue by michaeldsmith** [sandflow/rfc-j2k-scl#7]
I think this text should say "Figure 2 specifies the structure of the Main Packet Payload Header. Fields are interpretted..."

![image](https://github.com/sandflow/rfc-j2k-scl/assets/37905569/16d40ac6-8475-498d-b7d6-5d4f69ae7819)

**Comment by palemieux** [comment]
Closed by 5d1de85df3275af79304a9d54fd2b3f09e46f2c3
