### ISSUE TITLE
7.9 NOTE editorial typo 

### ISSUE THREAD

**Issue by michaeldsmith** [sandflow/rfc-j2k-scl#8]
Section 7.9 NOTE has a typo

![image](https://github.com/sandflow/rfc-j2k-scl/assets/37905569/b5615869-eddb-4d87-96c6-3736247aaf76)

... bit rate even when code-block does not contribute code-bytes,

should be

... bit rate even when `a` code-block does not contribute code-bytes,

**Comment by palemieux** [comment]
Closed by 7f48d5c41e3b293bbd3a2185078fb00b8f5967fc
